version: 2

sources:
  - name: netfilxdb
    #database: '{{target.database}}' 
    database: netfilxdb
    schema: netfilxschema  
    tables:
      - name: dim_customer
      - name: dim_date
      - name: dim_store
      - name: fact_sales
      - name: fact_returns
      - name: dim_product
